### ISSUE TITLE
i want to train my custom dataset, how can??

### ISSUE THREAD

**Issue by KUKUDAS95** [Westlake-AI/openmixup#62]
i want use adautomix with my custom dataset.
and i want to use adautomix in my independent environment.
how can??

please tell me about some guide

**Comment by Lupin1998** [comment]
Hi, @KUKUDAS95. Thanks for using OpenMixup. You can train with the custom dataset by making a meta list file and using `ImageNet` dataset. Please refer to [meta files](https://github.com/Westlake-AI/openmixup/releases/download/dataset/meta.zip) for the list file examples. Or you write a new dataset with a new data loading function as mentioned in [1_new_dataset](https://github.com/Westlake-AI/openmixup/blob/main/docs/en/tutorials/1_new_dataset.md) for writing a new dataset.

**Comment by KUKUDAS95** [comment]
how can control batch_size in configs/classification/imagenet/resnet/resnet50_4xb64_cos_ep100.py?

**Comment by KUKUDAS95** [comment]
do you know why occur this error?

Traceback (most recent call last):
  File "/mnt/4d055040-c192-46c7-906e-bebc0ed47c00/kchong/AIMA/openmixup/tools/train.py", line 208, in <module>
    main()
  File "/mnt/4d055040-c192-46c7-906e-bebc0ed47c00/kchong/AIMA/openmixup/tools/train.py", line 198, in main
    train_model(
  File "/mnt/4d055040-c192-46c7-906e-bebc0ed47c00/kchong/AIMA/openmixup/openmixup/apis/train.py", line 101, in train_model
    data_loaders = [
  File "/mnt/4d055040-c192-46c7-906e-bebc0ed47c00/kchong/AIMA/openmixup/openmixup/apis/train.py", line 102, in <listcomp>
    build_dataloader(ds, **data_loader_cfg) for ds in dataset
  File "/mnt/4d055040-c192-46c7-906e-bebc0ed47c00/kchong/AIMA/openmixup/openmixup/datasets/loader/build_loader.py", line 95, in build_dataloader
    worker_init_fn, num_workers=num_workers, rank=rank,
UnboundLocalError: local variable 'rank' referenced before assignment
